### PR TITLE
feat: enable users to pass a custom logger

### PR DESCRIPTION
**Pull request by jeswr**
This PR adds the feature of allowing users to pass a custom Logger to bashlib functions.

### CODE REVIEW

**Comment by jeswr** [comment]
@Dexagod could you please review this when you get the chance (I lack the permissions to add you as a reviewer)

**Comment by mielvds** [comment]
Thanks, looks good! Not a result of this PR, but I wonder whether we still need both the `writeErrorString` methods and the `(logger || console).error` constructs

**Comment by Dexagod** [comment]
I know I've been a tad inconsistent as well with my logging. 
I'll take a look at making it a bit more consistent over the whole codebase.

**Comment by jeswr** [comment]
>  I'll take a look at making it a bit more consistent over the whole codebase.

@Dexagod - just a point to consider is that I am using this to throw an error when `logger.error` is called.

**Comment by jeswr** [comment]
Thanks for merging this so fast btw; a release when you get the chance would be very useful :)

**Comment by Dexagod** [comment]
I've updated the npm package so it should be usable with a global install from the CLI already.
A full release however will require at least a partial test coverage, and fixing session refresh.
Not sure when I'll get to that sadly :/

**Pull request merged**
